# Generated by Django 5.0 on 2023-12-13 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsInfo',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_info_user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Admissions',
                'verbose_name_plural': 'Admissions',
            },
        ),
        migrations.CreateModel(
            name='AdmissionsInfoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/admissions_image')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_info_images', to='admissions.admissionsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsPage',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Admissions',
                'verbose_name_plural': 'Admissions',
            },
        ),
        migrations.AddField(
            model_name='admissionsinfo',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_info', to='admissions.admissionspage'),
        ),
        migrations.CreateModel(
            name='AdmissionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/admissions_image')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_images', to='admissions.admissionspage')),
            ],
        ),
    ]
